### ISSUE TITLE
Keys for doors.

### ISSUE THREAD

**Issue by MichaelYang-lyx** [ReoGrande/CSE3902#68]

**Comment by ReoGrande** [comment]
#70

**Comment by MichaelYang-lyx** [comment]
Now fix the number count when pickup keys.

**Comment by MichaelYang-lyx** [comment]
Key.SpecialType()=Default is also fixed. I just override the Clone method in key to create a key with special characteristics rather than normal staticitems.

**Comment by ReoGrande** [comment]
merged to main #70

**Comment by ReoGrande** [comment]
merged to main #70
